// <auto-generated />
using System;
using MarkdownGenQAs.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarkdownGenQAs.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.AccessShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DatasetItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionMask")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ShareToDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShareToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DatasetItemId");

                    b.HasIndex("DatasetId", "DatasetItemId", "ShareToUserId", "ShareToDepartmentId")
                        .IsUnique()
                        .HasFilter("\"DatasetItemId\" IS NOT NULL");

                    b.ToTable("AccessShares", (string)null);
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.ConversationThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ThreadId")
                        .IsUnique();

                    b.HasIndex("Title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("Threads", (string)null);
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountDocument")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TemplateMetadataId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TemplateMetadataId");

                    b.ToTable("Datasets", (string)null);
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.DatasetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    b.HasIndex("DatasetId", "Level");

                    b.ToTable("DatasetItems", (string)null);
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkContent")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DatasetItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GenQaCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenQaCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GenQaStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IndexingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IndexingCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IndexingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMetadataExtracted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOcred")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQaGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataContent")
                        .HasColumnType("text");

                    b.Property<string>("MetadataError")
                        .HasColumnType("text");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectKeyFilePdf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OcrCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OcrContent")
                        .HasColumnType("text");

                    b.Property<int>("OcrCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OcrStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessingTimeGenQa")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessingTimeIndexing")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessingTimeOcr")
                        .HasColumnType("integer");

                    b.Property<string>("QaContent")
                        .HasColumnType("text");

                    b.Property<string>("QaSummaryContent")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FileName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FileName"), new[] { "gin_trgm_ops" });

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.DocumentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("GenQaJobId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IndexingJobId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OcrJobId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StatusGenQa")
                        .HasColumnType("text");

                    b.Property<string>("StatusIndexing")
                        .HasColumnType("text");

                    b.Property<string>("StatusOcr")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("DocumentJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentJob_OcrBeforeIndexing", "\"StatusIndexing\" IS NULL\n                      OR \"StatusOcr\" = 'Succeeded'\n                      OR \"StatusIndexing\" NOT IN ('Processing', 'Succeeded')");
                        });
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.LogMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogsGenQa")
                        .HasColumnType("jsonb");

                    b.Property<string>("LogsIndexing")
                        .HasColumnType("jsonb");

                    b.Property<string>("LogsOcr")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("LogMessages", (string)null);
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.SystemStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("TotalDatasets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalDocuments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("TotalStorageUsage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("SystemStatistics", (string)null);
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.TemplateMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IndexKeys")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TemplateMetadatas", (string)null);
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.AccessShare", b =>
                {
                    b.HasOne("MarkdownGenQAs.Models.Entities.Dataset", "Dataset")
                        .WithMany("AccessShares")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarkdownGenQAs.Models.Entities.DatasetItem", "DatasetItem")
                        .WithMany()
                        .HasForeignKey("DatasetItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dataset");

                    b.Navigation("DatasetItem");
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.Dataset", b =>
                {
                    b.HasOne("MarkdownGenQAs.Models.Entities.TemplateMetadata", "TemplateMetadata")
                        .WithMany("Datasets")
                        .HasForeignKey("TemplateMetadataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TemplateMetadata");
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.DatasetItem", b =>
                {
                    b.HasOne("MarkdownGenQAs.Models.Entities.Dataset", "Dataset")
                        .WithMany("Items")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarkdownGenQAs.Models.Entities.Document", "Document")
                        .WithOne("DatasetItem")
                        .HasForeignKey("MarkdownGenQAs.Models.Entities.DatasetItem", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MarkdownGenQAs.Models.Entities.DatasetItem", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dataset");

                    b.Navigation("Document");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.DocumentJob", b =>
                {
                    b.HasOne("MarkdownGenQAs.Models.Entities.Document", "Document")
                        .WithOne("DocumentJob")
                        .HasForeignKey("MarkdownGenQAs.Models.Entities.DocumentJob", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.LogMessage", b =>
                {
                    b.HasOne("MarkdownGenQAs.Models.Entities.Document", "Document")
                        .WithOne("LogMessage")
                        .HasForeignKey("MarkdownGenQAs.Models.Entities.LogMessage", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.Dataset", b =>
                {
                    b.Navigation("AccessShares");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.Document", b =>
                {
                    b.Navigation("DatasetItem");

                    b.Navigation("DocumentJob");

                    b.Navigation("LogMessage");
                });

            modelBuilder.Entity("MarkdownGenQAs.Models.Entities.TemplateMetadata", b =>
                {
                    b.Navigation("Datasets");
                });
#pragma warning restore 612, 618
        }
    }
}
