@MarkdownGenQAs_HostAddress = http://localhost:5184
@id = 00000000-0000-0000-0000-000000000000

### 1. Get All OCR Jobs
GET {{MarkdownGenQAs_HostAddress}}/api/v1/ocr-jobs
Accept: application/json

### 2. Get OCR Job by ID
GET {{MarkdownGenQAs_HostAddress}}/api/v1/ocr-jobs/{{id}}
Accept: application/json

### 3. Get OCR Job by Document ID
GET {{MarkdownGenQAs_HostAddress}}/api/v1/ocr-jobs/by-file/{{id}}
Accept: application/json

### 4. Get OCR Job by External OCR Job ID
GET {{MarkdownGenQAs_HostAddress}}/api/v1/ocr-jobs/by-external-file/ocr-job-external-id
Accept: application/json

### 5. Delete OCR Job
DELETE {{MarkdownGenQAs_HostAddress}}/api/v1/ocr-jobs/{{id}}
