@MarkdownGenQAs_HostAddress = http://localhost:5184
@documentId = ee85fd24-0606-4d2c-9264-949d05d15276

### Test Table Continuation for a Document
# Requires document with OcrContent filled
GET {{MarkdownGenQAs_HostAddress}}/api/v1/test/table-continuation/{{documentId}}
Accept: application/json
